### ISSUE TITLE
Recent CI runs are failing

### ISSUE THREAD

**Issue by dzeber** [mozilla/search-terms-sanitization#20]
Recently, CircleCI `build-and-push-image` jobs have been failing, eg. [this one](https://app.circleci.com/pipelines/github/mozilla/search-terms-sanitization/32/workflows/1c9f6fba-f6a7-487a-902e-3dfc29696ff3/jobs/44).

The "Initialize gcloud CLI" step fails with `ERROR: gcloud crashed (ValueError): No key could be detected.`

**Comment by dzeber** [comment]
@chelseatroy or @whd, do you have any thoughts?

**Comment by whd** [comment]
@jbuck rotated this key in early January for the CircleCI incident, so builds have probably been failing since then. I re-ran the job with SSH and determined that the issue was that the updated private key had all spaces removed and was therefore invalid i.e.`BEGIN PRIVATE KEY` and `END PRIVATE KEY` became `BEGINPRIVATEKEY` and `ENDPRIVATEKEY`. I imagine this is because of a minification step :jbuck took when adding the new key so that it would fit on one line.

I dumped the key, added back the spaces, updated the CircleCI Context, and re-ran the job, which pushed an image successfully, so I'm considering this fixed.
